name: 'Regen Builds'

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ regen-builds ]

jobs:
  regen:
    runs-on: ubuntu-latest

    steps:
      # third-party action that cancels previous runs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout titanium-builds
        uses: actions/checkout@v3

      - name: Retrieve the builds
        uses: tidev/titanium-builds-regen-action@v1
        with:
          output-dir: 'public/registry'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        id: committed
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Repository Dispatch
        if: steps.committed.outputs.changes_detected == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: deploy
          token: ${{ secrets.REGEN_BUILDS_DOCS_GITHUB_TOKEN }}
